In [3]:
import torch
from torch.utils import data 


In [4]:
def data_gen(w,b,nums): #@save
    X=torch.normal(0,1,(nums,len(w)))
    y=torch.mm(X,w)+b
    y+=torch.normal(0,0.1,y.shape)
    return X,y

In [54]:
batchsize=250
true_w=torch.tensor([2.,1.]).reshape(2,-1)
true_b=torch.tensor([3.])
features,labels=data_gen(true_w,true_b,1000)

In [55]:
#iterator
def iterator(data_array,batchsize,istrain=True):
    dataset=data.TensorDataset(*data_array)
    # data loader generate an iterater
    return data.DataLoader(dataset,batchsize,shuffle=istrain)

dataset=iterator([features,labels],batchsize,True)

In [106]:
## define model
from torch import nn
net=nn.Sequential(nn.Linear(2,1))

## fill numbers
net[0].weight.data.normal_(0,1)
net[0].bias.data.fill_(0)

## define loss fun
loss=nn.L1Loss(reduction='mean')
## optimal method
trainer=torch.optim.SGD(net.parameters(),0.1)

In [111]:
epoch=30
for i in range(epoch):
    for X,y in dataset:
        l=loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        print(net[0].weight.grad)
        break
        trainer.step()
#print(net[0].weight.data)

tensor([[-0.2666,  0.0065]])
tensor([[-0.2667,  0.0711]])
tensor([[-0.2784,  0.0957]])
tensor([[-0.2015, -0.0496]])
tensor([[-0.1891,  0.0323]])
tensor([[-0.2488,  0.0284]])
tensor([[-0.2314,  0.0385]])
tensor([[-0.1671,  0.0527]])
tensor([[-0.1709, -0.0527]])
tensor([[-0.1957,  0.0330]])
tensor([[-0.2384,  0.0386]])
tensor([[-0.3239,  0.0856]])
tensor([[-0.1906,  0.1304]])
tensor([[-0.2669, -0.0655]])
tensor([[-0.3095,  0.0274]])
tensor([[-0.1774,  0.0521]])
tensor([[-0.2363, -0.0019]])
tensor([[-0.2162,  0.0638]])
tensor([[-0.2443,  0.0852]])
tensor([[-0.3620, -0.0303]])
tensor([[-0.2884, -0.0151]])
tensor([[-0.2697, -0.0304]])
tensor([[-0.1664, -0.0467]])
tensor([[-0.1876,  0.0094]])
tensor([[-0.1582,  0.0466]])
tensor([[-0.2411, -0.0146]])
tensor([[-0.2056,  0.1099]])
tensor([[-0.2042,  0.0301]])
tensor([[-0.1663,  0.0463]])
tensor([[-0.1629, -0.0691]])


In [76]:
?torch.nn.Huber

Object `torch.nn.Huber` not found.


In [45]:
?torch.nn.MSELoss

Init signature: torch.nn.MSELoss(size_average=None, reduce=None, reduction: str = 'mean') -> None
Docstring:     
Creates a criterion that measures the mean squared error (squared L2 norm) between
each element in the input :math:`x` and target :math:`y`.

The unreduced (i.e. with :attr:`reduction` set to ``'none'``) loss can be described as:

.. math::
    \ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
    l_n = \left( x_n - y_n \right)^2,

where :math:`N` is the batch size. If :attr:`reduction` is not ``'none'``
(default ``'mean'``), then:

.. math::
    \ell(x, y) =
    \begin{cases}
        \operatorname{mean}(L), &  \text{if reduction} = \text{'mean';}\\
        \operatorname{sum}(L),  &  \text{if reduction} = \text{'sum'.}
    \end{cases}

:math:`x` and :math:`y` are tensors of arbitrary shapes with a total
of :math:`n` elements each.

The mean operation still operates over all the elements, and divides by :math:`n`.

The division by :math:`n` can be avoided if one sets ``reductio